name: pfr-ml
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - pyyaml
  - rdkit
  - pytorch
  - pytorch-lightning
  - pip:
      - torch-geometric
      - torchmetrics
